### PR TITLE
Added FREE ChatGPT

### PR DESCRIPTION
**Pull request by LabGuy94**
Code is quite messy so if you want to make improvements go right ahead.
I reversed the undocumented api found at https://chat.openai.com/chat.

### CODE REVIEW

**Comment by JusticeRage** [comment]
Thanks a lot for the PR! I'll have to think about it a little. The main issue I see is that if the undocumented API breaks at some point, the script may become unusable. I'll think about the options ASAP.

**Comment by LabGuy94** [comment]
Sounds Good!

**Comment by LabGuy94** [comment]
> Thanks a lot for the PR! I'll have to think about it a little. The main issue I see is that if the undocumented API breaks at some point, the script may become unusable. I'll think about the options ASAP.

There is an option to use the paid or undocumented api by changing the bool at the start of the script

**Comment by Chaoses-Ib** [comment]
There is also a package: https://github.com/acheong08/ChatGPT

**Comment by ChrisNonyminus** [comment]
OpenAI seems to block the requests now...

**Comment by JusticeRage** [comment]
Yes, this is precisely what I feared would happen.
Let's see how the situation evolves, but I would be surprised to see them allow easy and free access to an otherwise billed service.

**Comment by JusticeRage** [comment]
Sure, but you can see how it will require a lot of attention to keep up with the cat and mouse game... I'd rather work on new features than have to replace libraries and implement hacks every other day.

**Comment by LabGuy94** [comment]
> OpenAI seems to block the requests now...



> Sure, but you can see how it will require a lot of attention to keep up with the cat and mouse game... I'd rather work on new features than have to replace libraries and implement hacks every other day.

That is fair enough, if you desire to you can close the PR.

**Pull request closed without merging**
